# Generated by Django 5.2.15 on 2026-07-01 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='number_student',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
